### ISSUE TITLE
New symbols

### ISSUE THREAD

**Issue by QCaudron** [QCaudron/ivanatrumpalot#16]
Sometimes, a tweet will contain a symbol that wasn't in the corpus. We should :
- correctly strip unicode characters
- ensure the **alphabet** has all letters and numbers, even if they aren't in the corpus
- strip anything not in the corpus after this

**Comment by sempwn** [comment]
Added space in place of unicode characters that are found in corpus. Should fix this. #19

**Comment by QCaudron** [comment]
Awesome. I've added a set of basic essential characters to the alphabet on creation.
